export const quotesArray = [
	"Let our New Year’s resolution be this: We will be there for one another as fellow members of humanity, in the finest sense of the word. — Göran Persson",
	"Whatever it is you’re scared of doing, do it. Make your mistakes, next year and forever. — Neil Gaiman",
	"Cheers to a new year and another chance for us to get it right. — Oprah Winfrey",
	"The bad news is time flies. The good news is you’re the pilot. — Michael Altshuler",
	"For last year’s words belong to last year’s language and next year’s words await another voice. — T.S. Eliot",
	"New Year—a new chapter, new verse, or just the same old story? Ultimately we write it. The choice is ours. — Alex Morritt",
	"The road ahead is not some predetermined path that I am forced to trod, but it is a rich byway that I can help create. — Craig D. Lounsbrough",
	"What the New Year brings to you will depend a great deal on what you bring to the New Year. — Vern McLellan",
	"This is a new year. A new beginning. And things will change. — Taylor Swift",
	"Write it on your heart that every day is the best day in the year. — Ralph Waldo Emerson",
	"In our perfect ways. In the ways we are beautiful. In the ways we are human. We are here. Happy New Year’s. Let’s make it ours. — Beyoncé",
	"Good resolutions are simply checks that men draw on a bank where they have no account. — Oscar Wilde",
	"Year’s end is neither an end nor a beginning but a going on, with all the wisdom that experience can instill in us. — Oprah Winfrey",
	"New Year’s Day: Now is the accepted time to make your regular annual good resolutions. Next week you can begin paving hell with them as usual. — Mark Twain",
	"A new heart for a New Year, always! — Charles Dickens",
	"One resolution I have made, and try always to keep, is this: To rise above the little things. — John Burroughs",
	"Tomorrow is the first blank page of a 365-page book. Write a good one. — Brad Paisley",
	"May all your troubles last as long as your New Year’s resolutions. — Joey Adams",
	"New year is the glittering light to brighten the dream-lined pathway of future. — Munia Khan",
	"With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
	"Youth is when you’re allowed to stay up late on New Year’s Eve. Middle age is when you’re forced to. — Bill Vaughan",
	"May the New Year bring you courage to break your resolutions early. — Aleister Crowley",
	"Always bear in mind that your own resolution to succeed is more important than any other. — Abraham Lincoln",
	"The object of a new year is not that we should have a New Year. It is that we should have a new soul. — G. K. Chesterton",
	"Be at war with your vices, at peace with your neighbors, and let every New Year find you a better man. — Benjamin Franklin",
	"Every time you tear a leaf off a calendar, you present a new place for new ideas. — Charles Kettering",
	"Take a leap of faith and begin this wondrous New Year by believing. — Sarah Ban Breathnach",
	"A New Year…a fresh, clean start. It’s like having a big white sheet of paper to draw on. — Bill Watterson",
	"Kindness, kindness, kindness. I want to make a New Year's prayer, not a resolution. I'm praying for courage. — Susan Sontag",
	"The New Year stands before us, like a chapter in a book, waiting to be written. — Melody Beattie",
	"It wouldn’t be New Year’s if I didn’t have regrets. — William Thomas",
	"Enter this new year with a gratitude for this new chance to create your dreams. — Avina Celeste",
	"The beginning is the most important part of the work. — Plato",
	"Happiness is too many things these days for anyone to wish it on anyone lightly. So, let’s just wish each other a New Year. — Judith Crist",
	"New Year’s Day is every man’s birthday. — Charles Lamb",
	"I would say happy New Year but it’s not happy, it’s exactly the same as last year except colder. — Robert Clark",
	"Celebrate endings, for they precede new beginnings. — Jonathan Lockwood Huie",
	"A very wise man once told me that you can’t look back—you just have to put the past behind you and find something better in your future. — Jodi Picoult",
	"The magic in new beginnings is truly the most powerful of them all. — Josiyah Martin",
	"In order to be successful in the new year, stay focused, develop a positive attitude, and be passionate with your dreams. — Bamigboye Olurotimi",
	"Never tell your resolution beforehand, or it’s twice as onerous a duty. — John Selden",
	"What a wonderful thought it is that some of the best days of our lives haven't even happened yet. — Anne Frank",
	"You can get excited about the future. The past won’t mind. — Hillary DePiano",
	"Though no one can go back and make a brand-new start, anyone can start from now and make a brand-new ending. — Carl Bard",
	"I like the dreams of the future better than the history of the past. — Thomas Jefferson",
	"It is never too late to be what you might have been. — George Eliot",
	"Don’t live the same year 75 times and call it a life. — Robin Sharma",
	"Learn from yesterday, live for today, hope for tomorrow. — Albert Einstein",
	"Every new beginning comes from some other beginning’s end. — Seneca",
	"No matter how hard the past, you can always begin again. — Buddha",
	"I thought one of the perks of having a family was that you didn’t have to spend New Year’s Eve alone with Chinese food. — Miranda Hobbes, Sex And The City",
	"To the old, long life and treasure; to the young, all health and pleasure. — Ben Jonson",
	"Ring out the old, ring in the new. Ring, happy bells, across the snow. The year is going, let him go; ring out the false, ring in the true. — Alfred Lord Tennyson",
	"Sometimes a year has been so disastrous and so terrible that entering a new year will automatically mean entering a wonderful year! — Mehmet Murat Ildan",
	"The first step towards getting somewhere is to decide you're not going to stay where you are. — J.P. Morgan",
	"New beginnings are in order, and you are bound to feel some level of excitement as new chances come your way. — Auliq Ice",
	"We spend January 1st walking through our lives, room by room, drawing up a list of work to be done, cracks to be patched. Maybe this year, to balance the list, we ought to walk through the rooms of our lives...not looking for flaws but for potential. — Ellen Goodman",
	"Resolve to keep happy, and your joy and you shall form an invincible host against difficulties. — Hellen Keller",
	"Each year's regrets are envelopes in which messages of hope are found for the new year. — John R. Dallas Jr.",
	"Year's end is neither an end nor a beginning but a going on. — Hal Borland",
	"You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
	"The secret of change is to focus all of your energy, not on fighting the old, but on building the new. — Dan Millman",
	"New Year’s resolution: To tolerate fools more gladly, provided this does not encourage them to take up more of my time. — James Agate",
	"Packaged inside of every mistake there lays a great lesson. And while I don’t want to take the mistake into the New Year, I most certainly want to take the lesson that’s packaged inside of it. — Craig D. Lounsbrough",
	"We will open the book. Its pages are blank. We are going to put words on them ourselves. The book is called Opportunity and its first chapter is New Year's Day. — Edith Lovejoy Pierce",
	"This year's book, at midnight turns to footnote in the next. — Terri Guillemets",
	"You are never too old to reinvent yourself. — Steve Harvey",
	"Make New Year's goals. Dig within, and discover what you would like to have happen in your life this year. This helps you do your part. It is an affirmation that you're interested in fully living life in the year to come. — Melody Beattie",
	"A New Year has tiptoed in. Let’s go forward to meet it. — Anusha Atukorala",
	"Approach the new year with resolve to find the opportunities hidden in each new day. — Michael Josephson",
	"Too much of anything is bad, but too much Champagne is just right. — F. Scott Fitzgerald",
	"Begin doing what you want to do now. We are not living in eternity. We have only this moment, sparkling like a star in our hand and melting like a snowflake. — Francis Bacon Sr.",
	"Packaged inside of every mistake there lays a great lesson. And while I don’t want to take the mistake into the New Year, I most certainly want to take the lesson that’s packaged inside of it. — Craig D. Lounsbrough",
	"We must be willing to get rid of the life we’ve planned, so as to have the life that is waiting for us. The old skin has to be shed before the new one can come. — Joseph Campbell",
	"Make New Year's goals. Dig within, and discover what you would like to have happen in your life this year. This helps you do your part. It is an affirmation that you're interested in fully living life in the year to come. — Melody Beattie",
	"A New Year has tiptoed in. Let’s go forward to meet it. — Anusha Atukorala",
	"Approach the new year with resolve to find the opportunities hidden in each new day. — Michael Josephson",
	"Too much of anything is bad, but too much Champagne is just right. — F. Scott Fitzgerald",
	"Begin doing what you want to do now. We are not living in eternity. We have only this moment, sparkling like a star in our hand and melting like a snowflake. — Francis Bacon Sr.",
	"Packaged inside of every mistake there lays a great lesson. And while I don’t want to take the mistake into the New Year, I most certainly want to take the lesson that’s packaged inside of it. — Craig D. Lounsbrough",
	"We must be willing to get rid of the life we’ve planned, so as to have the life that is waiting for us. The old skin has to be shed before the new one can come. — Joseph Campbell",
	"Character is the ability to carry out a good resolution long after the excitement of the moment has passed. — Cavett Roberts",
	"We will open the book. Its pages are blank. We are going to put words on them ourselves. The book is called Opportunity and its first chapter is New Year's Day. — Edith Lovejoy Pierce",
	"This year's book, at midnight turns to footnote in the next. — Terri Guillemets",
	"You are never too old to reinvent yourself. — Steve Harvey",
	"Make New Year's goals. Dig within, and discover what you would like to have happen in your life this year. This helps you do your part. It is an affirmation that you're interested in fully living life in the year to come. — Melody Beattie",
	"A New Year has tiptoed in. Let’s go forward to meet it. — Anusha Atukorala",
	"Approach the new year with resolve to find the opportunities hidden in each new day. — Michael Josephson",
	"Too much of anything is bad, but too much Champagne is just right. — F. Scott Fitzgerald",
	"Begin doing what you want to do now. We are not living in eternity. We have only this moment, sparkling like a star in our hand and melting like a snowflake. — Francis Bacon Sr.",
	"Packaged inside of every mistake there lays a great lesson. And while I don’t want to take the mistake into the New Year, I most certainly want to take the lesson that’s packaged inside of it. — Craig D. Lounsbrough",
	"We must be willing to get rid of the life we’ve planned, so as to have the life that is waiting for us. The old skin has to be shed before the new one can come. — Joseph Campbell",
	"Character is the ability to carry out a good resolution long after the excitement of the moment has passed. — Cavett Roberts"
      ];
      
